M48
; DRILL file {KiCad 7.0.7} date Fri Jun 14 09:16:20 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-14T09:16:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X78.7Y-79.45
T2
X77.5Y-67.0
X77.5Y-114.0
X224.5Y-67.0
X224.5Y-114.0
T0
M30
