M48
; DRILL file {KiCad 7.0.7} date Tue Apr  9 00:53:39 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-09T00:53:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X78.7Y-79.45
T2
X77.5Y-67.5
X77.5Y-113.5
X224.5Y-67.5
X224.5Y-113.5
T0
M30
